[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[functions]
  node_bundler = "esbuild"

[functions.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/registerations"
  to = "/registrations"
  status = 301
  force = true
