/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForFoundersRouteImport } from './routes/for-founders'
import { Route as RegisterationsRouteImport } from './routes/registerations'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as WebinarsIndexRouteImport } from './routes/webinars/index'
import { Route as WebinarsSlugRouteImport } from './routes/webinars/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForFoundersRoute = ForFoundersRouteImport.update({
  id: '/for-founders',
  path: '/for-founders',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterationsRoute = RegisterationsRouteImport.update({
  id: '/registerations',
  path: '/registerations',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WebinarsIndexRoute = WebinarsIndexRouteImport.update({
  id: '/webinars/',
  path: '/webinars/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebinarsSlugRoute = WebinarsSlugRouteImport.update({
  id: '/webinars/$slug',
  path: '/webinars/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/for-founders': typeof ForFoundersRoute
  '/registerations': typeof RegisterationsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/webinars/$slug': typeof WebinarsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/webinars/': typeof WebinarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/for-founders': typeof ForFoundersRoute
  '/registerations': typeof RegisterationsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/webinars/$slug': typeof WebinarsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/webinars': typeof WebinarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/for-founders': typeof ForFoundersRoute
  '/registerations': typeof RegisterationsRoute
  '/thank-you': typeof ThankYouRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/webinars/$slug': typeof WebinarsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/webinars/': typeof WebinarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/for-founders'
    | '/registerations'
    | '/thank-you'
    | '/admin'
    | '/blog/$slug'
    | '/webinars/$slug'
    | '/blog/'
    | '/webinars/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/for-founders'
    | '/registerations'
    | '/thank-you'
    | '/admin'
    | '/blog/$slug'
    | '/webinars/$slug'
    | '/blog'
    | '/webinars'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/for-founders'
    | '/registerations'
    | '/thank-you'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/webinars/$slug'
    | '/blog/'
    | '/webinars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForFoundersRoute: typeof ForFoundersRoute
  RegisterationsRoute: typeof RegisterationsRoute
  ThankYouRoute: typeof ThankYouRoute
  BlogSlugRoute: typeof BlogSlugRoute
  WebinarsSlugRoute: typeof WebinarsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  WebinarsIndexRoute: typeof WebinarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-founders': {
      id: '/for-founders'
      path: '/for-founders'
      fullPath: '/for-founders'
      preLoaderRoute: typeof ForFoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registerations': {
      id: '/registerations'
      path: '/registerations'
      fullPath: '/registerations'
      preLoaderRoute: typeof RegisterationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webinars/': {
      id: '/webinars/'
      path: '/webinars'
      fullPath: '/webinars/'
      preLoaderRoute: typeof WebinarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webinars/$slug': {
      id: '/webinars/$slug'
      path: '/webinars/$slug'
      fullPath: '/webinars/$slug'
      preLoaderRoute: typeof WebinarsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForFoundersRoute: ForFoundersRoute,
  RegisterationsRoute: RegisterationsRoute,
  ThankYouRoute: ThankYouRoute,
  BlogSlugRoute: BlogSlugRoute,
  WebinarsSlugRoute: WebinarsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  WebinarsIndexRoute: WebinarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
